//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLAWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Registration
    {
        public int Registration_ID { get; set; }
        public Nullable<int> Transaction_ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> User_Code { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
