//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLAWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Course_Feedback
    {
        public int Feedback_ID { get; set; }

        [Display(Name = "Course")]
        public Nullable<int> Course_ID { get; set; }

        [Display(Name = "Submitted By")]
        public string Id { get; set; }

        [Display(Name = "Teacher")]
        public Nullable<int> Teacher_ID { get; set; }

        [Display(Name = "Marketing")]
        public string Course_Marketing { get; set; }

        [Display(Name = "Registration Type")]
        public Nullable<bool> Course_Registration_Type { get; set; }

        [Display(Name = "Course Rating")]
        public Nullable<int> Course_Rating { get; set; }

        [Display(Name = "Comments")]
        [DataType(DataType.MultilineText)]
        public string Student_Comment { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Course Cours { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
