//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLAWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Types
    {
        public Event_Types()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Event_Type_ID { get; set; }
        public string Event_Description { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
