//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLAWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Event_Registration = new HashSet<Event_Registration>();
        }
    
        public int Event_ID { get; set; }
        public string Event_Type { get; set; }
        public string Event_Desc { get; set; }
        public string Event_Date { get; set; }
        public string Event_Time { get; set; }
        public Nullable<int> Tickets_Sold { get; set; }
        public Nullable<int> Max_Tickets { get; set; }
        public Nullable<float> Event_Cost { get; set; }
        public string Event_Location { get; set; }
        public string Event_Notes { get; set; }
    
        public virtual ICollection<Event_Registration> Event_Registration { get; set; }
    }
}
