//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLAWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Event_Feedback
    {
        public int Feedback_ID { get; set; }

        [Display(Name = "Event")]
        public Nullable<int> Event_ID { get; set; }

        [Display(Name = "User")]
        public string Id { get; set; }

        [Display(Name = "Marketing")]
        public string Event_Marketing { get; set; }

        [Display(Name = "Registration Type")]
        public Nullable<bool> Event_Registration_Type { get; set; }

        [Display(Name = "Rating")]
        public Nullable<int> Event_Rating { get; set; }

        [Display(Name = "Comment")]
        public string Student_Comment { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Event Event { get; set; }
    }
}
