//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLAWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOLADBEntities : DbContext
    {
        public LOLADBEntities()
            : base("name=LOLADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course_Registration> Course_Registration { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Event_Registration> Event_Registration { get; set; }
        public virtual DbSet<Event_Types> Event_Types { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
