//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLAWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Course_Feedback = new HashSet<Course_Feedback>();
            this.Courses = new HashSet<Course>();
        }
    
        public int Teacher_ID { get; set; }
        public string Id { get; set; }
        public Nullable<int> SSN { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Course_Feedback> Course_Feedback { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
