// <auto-generated />
namespace LOLAWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NameFirstName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameFirstName));
        
        string IMigrationMetadata.Id
        {
            get { return "201510020101393_NameFirstName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
